import React, { useState } from 'react';
import { ActivityIndicator, Image, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { redefinirPasswordAdministrador, solicitarRecuperacaoAdministrador } from '../../services/adminAuthService';
import { useResponsiveContent } from '../../hooks/useResponsive';

export default function RecuperarPasswordScreen({ navigation }: any) {
  const { isDesktop } = useResponsiveContent(20);
  const [etapa, setEtapa] = useState<1 | 2>(1); const [email, setEmail] = useState(''); const [code, setCode] = useState(''); const [password, setPassword] = useState(''); const [confirmacao, setConfirmacao] = useState(''); const [mostrar, setMostrar] = useState(false); const [carregando, setCarregando] = useState(false); const [erro, setErro] = useState<string | null>(null); const [sucesso, setSucesso] = useState<string | null>(null);
  async function enviarEmail() { if (!email.trim()) return setErro('Informe o e-mail do administrador.'); setErro(null); setSucesso(null); setCarregando(true); try { const r = await solicitarRecuperacaoAdministrador(email); setEtapa(2); setSucesso(r.message); } catch (e) { setErro(e instanceof Error ? e.message : 'Não foi possível enviar o código.'); } finally { setCarregando(false); } }
  async function redefinir() { if (password.length < 8) return setErro('A nova palavra-passe deve ter pelo menos 8 caracteres.'); if (password !== confirmacao) return setErro('As palavras-passe não coincidem.'); setErro(null); setCarregando(true); try { await redefinirPasswordAdministrador(email, code, password); setSucesso('Palavra-passe redefinida. Pode entrar novamente.'); setTimeout(() => navigation.replace('LoginAdministrador'), 1200); } catch (e) { setErro(e instanceof Error ? e.message : 'Não foi possível redefinir a palavra-passe.'); } finally { setCarregando(false); } }
  return <KeyboardAvoidingView style={styles.container} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}><ScrollView contentContainerStyle={[styles.scroll, isDesktop && { maxWidth: 440, width: '100%', alignSelf: 'center' }]} keyboardShouldPersistTaps="handled"><View style={styles.card}><Image source={require('../../../assets/ejc-print-logo.png')} style={styles.logo} resizeMode="contain" /><View style={styles.eyebrow}><Ionicons name="shield-checkmark-outline" size={18} color="#147D64" /><Text style={styles.eyebrowText}>ÁREA ADMINISTRATIVA</Text></View><Text style={styles.title}>Redefinir palavra-passe</Text><Text style={styles.subtitle}>{etapa === 1 ? 'Informe o e-mail do administrador para receber o código.' : 'Digite o código recebido e crie uma nova palavra-passe.'}</Text><Text style={styles.label}>E-mail</Text><TextInput style={styles.input} value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" editable={etapa === 1 && !carregando} placeholder="E-mail do administrador" />{etapa === 2 && <><Text style={styles.label}>Código de recuperação</Text><TextInput style={styles.input} value={code} onChangeText={setCode} autoCapitalize="characters" placeholder="Código recebido por e-mail" editable={!carregando} /><Text style={styles.label}>Nova palavra-passe</Text><View style={styles.password}><TextInput style={styles.passwordInput} value={password} onChangeText={setPassword} secureTextEntry={!mostrar} placeholder="Mínimo de 8 caracteres" editable={!carregando} /><Pressable style={styles.eye} onPress={() => setMostrar(!mostrar)}><Ionicons name={mostrar ? 'eye-off-outline' : 'eye-outline'} size={22} color="#627D98" /></Pressable></View><Text style={styles.label}>Confirmar palavra-passe</Text><TextInput style={styles.input} value={confirmacao} onChangeText={setConfirmacao} secureTextEntry={!mostrar} placeholder="Repita a nova palavra-passe" editable={!carregando} /></>}{erro && <Text style={styles.error}>{erro}</Text>}{sucesso && <Text style={styles.success}>{sucesso}</Text>}<Pressable style={[styles.button, carregando && styles.disabled]} disabled={carregando} onPress={etapa === 1 ? enviarEmail : redefinir}>{carregando ? <ActivityIndicator color="#FFF" /> : <Text style={styles.buttonText}>{etapa === 1 ? 'Enviar código' : 'Redefinir palavra-passe'}</Text>}</Pressable><Pressable onPress={() => navigation.goBack()} style={styles.back}><Text style={styles.backText}>Voltar ao login</Text></Pressable></View></ScrollView></KeyboardAvoidingView>;
}

const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: '#F5F7FA', padding: 20 }, scroll: { flexGrow: 1, justifyContent: 'center', paddingVertical: 24 }, card: { backgroundColor: '#FFF', borderRadius: 16, padding: 22, borderWidth: 1, borderColor: '#E6EAF0' }, logo: { width: 170, height: 60, alignSelf: 'flex-start', marginBottom: 12 }, eyebrow: { flexDirection: 'row', alignItems: 'center', gap: 7, marginBottom: 12 }, eyebrowText: { color: '#147D64', fontSize: 12, fontWeight: 'bold' }, title: { color: '#102A43', fontSize: 25, fontWeight: 'bold' }, subtitle: { color: '#627D98', marginTop: 7, marginBottom: 22, lineHeight: 20 }, label: { color: '#243B53', fontSize: 13, fontWeight: '600', marginBottom: 6 }, input: { borderWidth: 1, borderColor: '#D9E2EC', borderRadius: 10, color: '#102A43', padding: 13, marginBottom: 14, backgroundColor: '#FBFCFE' }, password: { position: 'relative', marginBottom: 14 }, passwordInput: { borderWidth: 1, borderColor: '#D9E2EC', borderRadius: 10, color: '#102A43', padding: 13, paddingRight: 48, backgroundColor: '#FBFCFE' }, eye: { position: 'absolute', right: 4, top: 2, bottom: 2, width: 44, justifyContent: 'center', alignItems: 'center' }, error: { color: '#B42318', marginBottom: 12 }, success: { color: '#147D64', marginBottom: 12, lineHeight: 19 }, button: { backgroundColor: '#102A43', minHeight: 48, borderRadius: 10, alignItems: 'center', justifyContent: 'center' }, disabled: { opacity: 0.7 }, buttonText: { color: '#FFF', fontWeight: 'bold' }, back: { alignItems: 'center', padding: 16 }, backText: { color: '#1D4ED8', fontWeight: '600' } });
